In [1]:
# Creating arrays

In [7]:
#np.arrays
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#2d and 3d

b = np.array([[1,2,3],[5,6,7]])
print(b)

[[1 2 3]
 [5 6 7]]


In [9]:
c = np.array([[[1,2,3],[3,4,5],[5,6,7]]])
print(c)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [10]:
#dtype

np.array([1,2,3],dtype = float)

np.array([1,2,3] , dtype =bool) #python treats any non zero value as true

array([ True,  True,  True])

In [11]:
#np.arange - acts like creating numpy array  by using range function(range func exact)

In [12]:
np.arange(1,9,1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [13]:
#with reshape say i want to create a 5*2 matrix

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
#np.ones and np.zeroes ( used mainly for intialization ex: nueral network)

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.random.random((3,4))

array([[0.54826546, 0.47312282, 0.99835753, 0.23258738],
       [0.88024089, 0.48091676, 0.45221459, 0.80935235],
       [0.00931768, 0.98055562, 0.88949026, 0.19822701]])

In [17]:
#np.linspace ( linear space)(lowerrange, upperrange , how many i want)
np.linspace(-10,10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [18]:
#np.identity : diagonal items are 1 rest is zero

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#ARRAY ATTRIBUTES

In [20]:
a1= np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [21]:
#ndim

a1.ndim
a2.ndim
a3.ndim

3

In [22]:
#shape

print(a3.shape)

(2, 2, 2)


In [23]:
#size

a3.size

8

In [24]:
#CHANGING DATA TYPE

In [25]:
#astype

a3.dtype

dtype('int32')

In [26]:
#changing data type
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
#array operations
a1 = np.arange(8).reshape(2,4)

In [28]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
#scalar operations

a1*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [30]:
#relational
a2 > 5 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
a2.resize(8).reshape(2,4)
a1+a2


ValueError: cannot resize this array: it does not own its data

In [32]:
a4 = np.arange(8).reshape(2,4)

In [33]:
#relational operations 

a1+a4

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [34]:
#min/max/sum/prod

np.max(a1)
np.min(a1) # min of the entire array
np.prod(a1)
np.sum(a1)

28

In [35]:
np.min(a1,axis =1) # min of every row # 0 is column # 1 is row

array([0, 4])

In [36]:
np.min(a1,axis =0) # min of every column # 0 is column # 1 is row

array([0, 1, 2, 3])

In [37]:
#trignometric functions

np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [38]:
#dot product

a6= np.arange(12).reshape(3,4)
a7 = np.arange(12).reshape(4,3)

np.dot(a6,a7)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [39]:
#log and exponents

np.log(a1)

C:\Users\anush\AppData\Local\Temp\ipykernel_31072\2770063862.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015]])

In [40]:
#round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[ 86.,  73.,  93.],
       [100.,  44.,  29.]])

In [41]:
np.var(a1, axis=1)
 

array([1.25, 1.25])

In [47]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[-1]

9

In [51]:
print(a2)
a2[0,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


1

In [53]:
a2[1,2]

6

In [54]:
a3[1,1]

array([6, 7])

In [59]:
#Indexing and slicing
#same like python lists
a1[2:10 :2]

array([2, 4, 6, 8])

In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
#slicing in 2d array
a2[1,:] #need 2nd row

array([4, 5, 6, 7])

In [62]:
a2[:,2] #need column 3 

array([ 2,  6, 10])

In [66]:
a2[1:,1:3]#need column 1 and 2 , therefor 1:3 where 3 is not included

array([[ 5,  6],
       [ 9, 10]])

In [69]:
#suppose in a2 we need 0,3,8,11

a2[::2,::3] # [rows eveything with interval of 2,columns everything with interval of 3]

array([[ 0,  3],
       [ 8, 11]])

In [78]:
# a2 we need 1,3,9,11

a2[::,1::3]

array([[ 1,  3],
       [ 9, 11]])

In [80]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
a3= np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
# if we need 1st 2d array 2nd row


a3[0,1,:]

array([3, 4, 5])

In [98]:
a3[1,:,1:2] # 2nd 2d array all rows, wand column 1

array([[10],
       [13],
       [16]])

In [99]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [100]:
#iteration on numpy array

In [101]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [105]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [106]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [108]:
for i in np.nditer(a3):  #this nd.iter will first convertt the 3d array to 2d and then convert it to 1d
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [109]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [110]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [111]:
#STACKING

In [117]:
#horizontal stacking : say we have a [2*2][2*2] , now we stack them horixonatlly , it'll become [2*4]

b1= np.arange(12).reshape(3,4)
b2= np.arange(12,24).reshape(3,4)
np.hstack((b1,b2,b2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23]])

In [119]:
#Vertical stacking : say we have a [2*2][2*2] , now we stack them vertical , it'll become [4*2]
np.vstack((b1,b2,b2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
#SPLITTING Point to note : hsplit is splitting vertically and v split is splitting horizontally

In [122]:
#horizontal splitting
# splitting b2 into two equal parts
print(b2)
np.hsplit(b2,2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [126]:
#vertical splitting
print(b1)
np.vsplit(b1,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [2]:
#Numpy array vs Python Lists
#why is numpy preferred than lists?
# 1. SPEED


import time
a = [i for i in range(10000000)]
b = [ i for i in range(100000000, 200000000)]
c= []
start  =time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time() -start)

3.1489646434783936


In [3]:
# same above code in numpy

import numpy as np 
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start  =time.time()
c =a+b
print(time.time() -start)

# # there is a lot of diff between list and array in terms of speed. 
# this is because numpy is a static array
# # whereas lists is a dynamic array. 
# Also, numpy is not a referential array as they do not store the value 
# is directly store in the memore and not in the address, whereas lists is a referential array  

0.11002111434936523


In [6]:
#2.Memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [14]:
a = np.arange(10000000, dtype = np.int8)
sys.getsizeof(a)
a.dtype

dtype('int8')

In [16]:
#fancy indexing
a1  = np.arange(24).reshape(6,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# now we want 1st 2nd 5, 6th row

print(a1[[0,1,4,5]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [16 17 18 19]
 [20 21 22 23]]


In [21]:
#suppose we need 1st column, 2nd column , 4th

a1[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

In [24]:
#boolean indexing  ( very important)

a= np.random.randint(1,100,24).reshape(6,4)

In [27]:
# find all the numbers greater than 50
print(a > 50)
a[a > 50]

[[False False False False]
 [False  True  True  True]
 [False  True False  True]
 [ True False  True False]
 [ True False  True  True]
 [ True False False False]]


array([81, 54, 88, 78, 99, 81, 64, 63, 74, 68, 94])

In [29]:
#find out only even numbers
a[a%2==0]

array([32, 54, 88, 18, 78,  8, 64, 38, 26, 74, 68, 94, 40, 22])

In [33]:
#find out all number greater than 50 and is even
a[(a>50) & (a%2 ==0)]  # 'and' is a logical and '&' is a bitwise and

array([54, 88, 78, 64, 74, 68, 94])

In [34]:
#find out all numbers divisible by 7
a[a%7 ==0]

array([63])

In [37]:
#Broadcasting - describes how numpy treats arrays wth diff shapes during arth operation
#same shape

a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [39]:
#diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]
