In [1]:
# Creating arrays

In [8]:
#np.arrays
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
#2d and 3d

b = np.array([[1,2,3],[5,6,7]])
print(b)

[[1 2 3]
 [5 6 7]]


In [12]:
c = np.array([[[1,2,3],[3,4,5],[5,6,7]]])
print(c)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [15]:
#dtype

np.array([1,2,3],dtype = float)

np.array([1,2,3] , dtype =bool) #python treats any non zero value as true

array([ True,  True,  True])

In [18]:
#np.arange - acts like creating numpy array  by using range function(range func exact)

In [19]:
np.arange(1,9,1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [25]:
#with reshape say i want to create a 5*2 matrix

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
#np.ones and np.zeroes ( used mainly for intialization ex: nueral network)

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [31]:
np.random.random((3,4))

array([[0.96455221, 0.30594701, 0.87785963, 0.91973558],
       [0.30427647, 0.35822141, 0.20406772, 0.90619657],
       [0.12812901, 0.82608792, 0.6703743 , 0.05468435]])

In [33]:
#np.linspace ( linear space)(lowerrange, upperrange , how many i want)
np.linspace(-10,10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [34]:
#np.identity : diagonal items are 1 rest is zero

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])